### ISSUE TITLE
Ragsdale QC

### ISSUE THREAD

**Issue by ndukler** [popgensims/stdpopsim#101]
Just checking @apragsdale , but N_0 is the population size of the archaic populations?

**Comment by ndukler** [comment]
Or is is the size of the ancestral african population? Or both? If it's not both I think I'm missing a population size parameter somewhere?

**Comment by apragsdale** [comment]
Sorry for the confusion.. the sizes along both archaic branches are equal to the initial reference size (N_0) before the modern human expansion.

Because we either didn't have or didn't use data from the archaic populations, we had little to no power to infer size changes along the archaic branches, so we chose to fix those as the reference ancestral size.

**Comment by ndukler** [comment]
Thanks!

**Comment by jeromekelleher** [comment]
I'm assuming this is OK to close; feel free to reopen if not.
