### ISSUE TITLE
Generic models

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#106]
#105 adds a ZigZag model to the list of human models. But, it's really a generic model. @andrewkern had the elegant idea that we could define some mixin models that we can combine with basic parameters for various organisms to get basic parameters for generation time, Ne etc. This seems feasible.

I suggest we define two more generic models so that we're not generalising on the basis of one case. Can we get some suggestions for what these should be please?

**Comment by Chris1221** [comment]
The issue of model complexity and the ability to be easily parameterised was also raised in the call re: @ndukler 's comments about organism-specific scaling. Are we looking to add in simpler models than the zig zag (i.e. I think @andrewkern mentioned a simple expansion model) or more complex models that might challenge the inference methods in some way (i.e. Simon Gravel mentioned that `msmc` probably wouldn't perform quite as well on a bottleneck model because the changes are more sudden. this might make it an interesting juxtaposition against the zigzag)?

**Comment by ndukler** [comment]
I think that quite a few of the generic models already have been implemented in a given species but for what it's worth here are some ones that kinda focus on the effect of a few parameters on inference:
 - Bottleneck -> recovery model
 - IM model

**Comment by andrewkern** [comment]
started some work over at #108

**Comment by andrewkern** [comment]
> I think that quite a few of the generic models already have been implemented in a given species but for what it's worth here are some ones that kinda focus on the effect of a few parameters on inference:
> 
>     * Bottleneck -> recovery model
> 
>     * IM model

@ndukler right now in #108 I have a constant size example and a two epoch model. if people are okay with what I have done so far I will continue to build these other generics

**Comment by andrewkern** [comment]
okay to close this down? we've now got this working for humans and i'm building out the capacity for arabidopsis later today

**Comment by jeromekelleher** [comment]
Sure, closing.
