### ISSUE TITLE
add a `backend` argument?

### ISSUE THREAD

**Issue by petrelharp** [popgensims/stdpopsim#133]
I think that we'll want to be able to specify which backend to use, once we have the ability to use a SLiM backend.

**Comment by grahamgower** [comment]
There will also need to be a way to specify backend specific parameters. It will get a little messy if they're all thrown in cli.py: top_parser. I propose that there be a `Backend` class, with an `add_backend()` method, so that various backend specific things can be specified (like currently exists for species or models). At a minimum, a backend would have a name, an empty list of CLI args, and implement a `simulate` function that follows the msprime.simulate API.

**Comment by jeromekelleher** [comment]
I agree we'll need a generic interface for the simulation engines (is "backend" a big vague?). Your ideas here seem very logical to me.

**Comment by grahamgower** [comment]
`SimulationEngine` is fine too.

**Comment by andrewkern** [comment]
closing this down as I believe https://github.com/popgensims/stdpopsim/pull/187 resolves this issue. feel free to reopen if necessary
