### ISSUE TITLE
Output SLiM code for population models

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#15]
The population models are current defined in terms of the [msprime APIs](https://msprime.readthedocs.io/en/stable/api.html#population-structure)  for defining populations, migration matrices and demographic events. Ideally, we would like to make these apply to SLiM also, so that we don't have to write the population models twice. Is it possible, even in principle, to output fragments of Eidos code which would implement the intended demography? 

Concretely, we'd have something like 
```python
import string
import stdpopsim
from stdpopsim import homo_sapiens

chrom = homo_sapiens.genome.chromosomes["chr22"]
model = homo_sapiens.GutenkunstThreePopOutOfAfrica()

slim_template = string.Template("""
initialize() {
    initializeTreeSeq();
    initializeMutationRate(0);
    initializeMutationType("m1", 0.5, "f", 0.0);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 1e8-1);
    initializeRecombinationRate($recombination_rate);
}

$demographic_model

5000late() {
     sim.treeSeqOutput("ex1_TS.trees");
}""")
slim_program = slim_template.substitute(
    recombination_rate=chrom.mean_recombination_rate,
    demographic_model=model.as_slim())
ts = pyslim.run(slim_program)
```

Any thoughts @petrelharp, @benhaller?

**Comment by jeromekelleher** [comment]
Oops, make that @bhaller.

**Comment by bhaller** [comment]
@jeromekelleher I don't see why not, in principle.  You can probably just generate "WF" type models (like the example you post above), which keeps things simpler than the non-Wright-Fisher model type.  And for simple models like this the auto-generated demographic code probably won't interact in unexpected ways with other aspects of the model since the rest of the model is very simple.  For a bit of guidance on how to proceed, I'd recommend looking at section 5.4 of the SLiM manual (available from messerlab.org/slim/), which shows how to write the Gravel model of human evolution in SLiM.  It has subpopulation splits, migration, and exponential growth.  Generalizing that to auto-generated code for any msprime demographic model will doubtless be annoying, but I don't see any fundamental obstacle, and it might prove to be a useful tool for others, too.  Conceivably you could write general Eidos code that would run the demographics driven by some sort of table-based input of the desired behavior, but the Eidos language might be a bit too limited for that sort of general-purpose code to be easy; generating the appropriate Eidos code in Python from the same data might prove easier.  But I'm not sure which approach is better; you might explore both at least a bit.  Anyway, let me know if you run into issues.

**Comment by jgallowa07** [comment]
@petrelharp, @andrewkern would this be a good project for me?

**Comment by jeromekelleher** [comment]
Closing this as it's covered by the ongoing SLiM engine project.
