### ISSUE TITLE
Add --help-species

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#168]
From @ndukler in #164:

> Once this gets pulled I will add a --help-defaults option so that people can see the default population size and generation time for the species (and citations). I realized I couldn't find an easy way for people to see it from the CLI when I was writing the tutorial.

Great idea @ndukler. Is 'defaults' the right name though? You can't override them from the CLI, so I'm not sure it is. They're the basic popgen properties of the species, so perhaps ``--help-species``? (Open to other ideas!)

**Comment by ndukler** [comment]
Sounds good to me.

**Comment by ndukler** [comment]
So I have it working nicely but I would like to add a bit of actual citation information for the default population sizes and generation times. Does anyone have some good references for those? @petrelharp @andrewkern @jeromekelleher

**Comment by jeromekelleher** [comment]
Good question!

**Comment by ndukler** [comment]
Okay, so I added the default mutation rates and recombination rates to this but then realized that there is no good way to automatically produce citations for any of this. In reality what I think would be best is the default mutation rates and recombination rates to operate on a genetic map object stored as `.default_genetic_map` instead of just being passed a string as they are right now. Then the citation could just be pulled from that for any given species. However this could require a bit of coding to set up. Is it worth it or should I just set up some properties like `.default_mutation_rate_cite` as placeholders that can be replaced under the hood later with a better solution? @jeromekelleher

**Comment by ndukler** [comment]
See PR #182

**Comment by ndukler** [comment]
Can we close this @jeromekelleher

**Comment by jeromekelleher** [comment]
FYI: adding "Closes #XYZ" in the body of the commit message will do this automatically.

**Comment by ndukler** [comment]
Ah, thanks! I was confused about how that worked :)
