### ISSUE TITLE
GenericIM API docs

### ISSUE THREAD

**Issue by agladstein** [popgensims/stdpopsim#181]
Maybe I'm missing it, but I don't think the class `GenericIM` is showing up in the API docs.
Should it be?

sub-issue https://github.com/popgensims/stdpopsim/issues/137

**Comment by jeromekelleher** [comment]
Yes, it should. It needs to be added to the ``docs/api.rst`` file to show up.

Note that here and in #180 we need to add a standard docstring to the class so that it gets documented here. There's two documentation strategies happening at once here: standard Python docstrings and the documentation generated for the Catalog. There's a question here as to what type of docs we need for the generic models. Since we'll mostly be using these from Python code, I think we should concentrate on Python API docs.

**Comment by agladstein** [comment]
Yes, I think that is fine. I think that the generic model tutorial (https://github.com/popgensims/stdpopsim/issues/173) + API docs will be sufficient for people. 

I can do this.
