### ISSUE TITLE
CLI Usage Statistics

### ISSUE THREAD

**Issue by reedacartwright** [popgensims/stdpopsim#230]
For future funding opportunities (NSF CIBR proposal) it would be good to have an estimate of the size of the user base of the CLI. Are there any recommendations for the best way to do this for the CLI? Do we even want to do this, since it involves tracking users?

Possibilities:

 - Encourage (require?) users to download a zip file that is attached to releases. Github will count the download statistics for this one.
 - Require users to register somewhere.
 - Add a 'phone-home' option that alerts when someone installs or first uses the CLI. This can be as simple as downloading a file from github, which allows us to count installations.

**Comment by jeromekelleher** [comment]
I would like to keep the installation options limited to the standard PyPI and conda-forge options. Conda gives you up-to-date statistics on downloads (e.g. https://anaconda.org/conda-forge/msprime) and it's possible to get download info from PyPI (but it's more involved). I'm not sure how meaningful these statistics are, since the vast majority of downloads will be from CI pipelines. Still, they give nice big numbers, which is all that you want really.

I think it's more important that we have a smooth and easy user experience than it is to have accurate user statistics, so I'd be against adding any complexities in terms of phoning home etc.

**Comment by jeromekelleher** [comment]
I'm going to close this; feel free to reopen if anyone things we should do more than use the conda/pypi download stats.
