### ISSUE TITLE
Implement ms simulation engine

### ISSUE THREAD

**Issue by grahamgower** [popgensims/stdpopsim#249]
It shouldn't be too difficult to translate `population_configurations`, `migration_matrix`, and `demographic_events` into an `ms` command line. The engine would thus also support the various simulators that accept ms parameters.

This supposes that either, (1) we don't care that the output is not a tree sequence, or (2) we have a ms-to-tree-sequence converter. Maybe someone has already done (2)?

And this is absolutely not a priority.

**Comment by jeromekelleher** [comment]
Well we definitely care that the output is a tree sequence. I think it'll degenerate into a big mess if we can't rely on tskit for handling the output. Having said that, we do have an ms-to-tskit conversion utility [here](https://github.com/tskit-dev/tsconvert/blob/master/tsconvert/newick.py#L28). It's not particularly efficient though.

The main question is, why? To me we'd be better of focusing effort on implementing missing features in msprime rather than hacking other simulators to work within the stdpopsim framework. That's just my (entirely biased) opinion though!

**Comment by andrewkern** [comment]
i completely agree @jeromekelleher. we definitely care that the output is a tree sequence. let's skip `ms` entirely.

**Comment by grahamgower** [comment]
Ok, no problem.
