### ISSUE TITLE
Where to locate standard simulation scripts (not the models)?

### ISSUE THREAD

**Issue by reedacartwright** [popgensims/stdpopsim#44]
If I understand the repo layout correctly,
1. `stdpopsim` holds models that can be used for generating simulations.
2. The example scripts in top-level folder are example scripts and don't create standardized simulations (which is why they don't dump the tree sequences at the end)

Where do the scripts for generating standard simulations belong? In `stdpopsim` or `analysis`?

**Comment by jeromekelleher** [comment]
Stdpopsim is a Python library for *defining* standard simulation models, including demographic models, recombination rate maps, etc. There's no concept of running the simulations. The examples files are just quick examples showing how to use the library. The ``analysis`` repo uses ``stdpopsim`` to run some simulations and then analyse these using some tools like stairwayplot, smc++, etc.

A key difference between ``stdpopsim`` and the ``analysis`` repo is that ``stdpopsim`` is intended to be a fully-fledged Python library, distributed on PyPI/conda etc. It's intended to be simple and high-quality so that it can be used for many years in lots of different ways. The ``analysis`` repo, on the other hand, is focused on the specific task for running some simulations and analysing them, and is inherently less reusable.

I don't think we're really addressed the "repository of downloadable benchmark simulations" question (ie., where the simulations have been run already). I think it's probably something we can kick down the road for Paper 2, to be honest. Having fully reproducible workflows and easily usable standard simulation models is already a big step forward...

**Comment by reedacartwright** [comment]
The name through me off then. I was expecting that `stdpopsim` would contain both a library defining standard simulation models and one or more scripts for generating specific standardized datasets.

**Comment by jeromekelleher** [comment]
> The name through me off then. I was expecting that stdpopsim would contain both a library defining standard simulation models and one or more scripts for generating specific standardized datasets.

These scripts would end up getting quite complicated I think, and probably pull in a lot of dependencies. For the sake of keeping making this repo "do one thing well", the actual deciding what to simulate, and how and where to store then would be better done in another repo.
