### ISSUE TITLE
Name abbreviation scheme

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#85]
As discussed in the meeting on June 04, part of the clunkiness of the CLI can be attributed to the lack of concise names. It would be nice to have a reasonably consistent scheme for describing what things are. 

Things we need to name:

## Species

Should be easy: ``h_sap``, ``d_mel`` etc? There must be well established notation for this somewhere that we can borrow?

## Population models 

It would be nice for the abbreviation to describe **what** the model is. Perhaps the first part would be the number of populations and the second some memorable abbreviation (3pop_ooa == Gutenkunst et al, 2pop_ooa == Tennyson)? Then perhaps if we have multiple 3pop_ooa models we could add a date of publication (3pop_ooa_2009), defaulting the shorter name to be synonymous with the more recent model?

Maybe the 'pop' bit in here is redundant: would ooa_3 be  better? I.e., first part is a descriptive abbreviation and the second part is the number of populations?

# Recombination maps

We could abbreviate HapMapIIGrch37 to  ``hm_37``?

**Comment by dschride** [comment]
For species, we could go with three letters for both of genus and species, which is what the UCSC Genome Browser does (e.g. panTro for chimp, though we could make it case insensitive). On the other hand this might cause some confusion in cases like human and Drosophila where a frequent Browser user might expect to be able to enter hg and dm rather than homSap or droMel. I am also fine with what you suggested as well--I am not aware of any standard for this.

For demog models I prefer the 2pop_ooa example as it is slightly more readable by someone who might not know our convention for abbreviations and three characters of redundancy won't kill anyway. I'm fine with your suggest about leaving the year out unless we need to resolve a collision.

**Comment by ndukler** [comment]
I actually think we should do something like `h_sapiens`, `d_melanogaster`, etc. because we're less likely to have some sort of ambiguity later if we add other species (e.g. a lot of species start with "mel") and it's not that long. With regard to titles I would argue for a slight variant of what @jeromekelleher proposed, `two_pop_ooa` instead of `2pop_ooa` if only because seeing a number at the start of a string makes me uncomfortable.

**Comment by jeromekelleher** [comment]
#110 added a 3+3 ID scheme for species as @dschride suggested above (great idea, thanks!). We want other ID schemes for models (#122) and genetic maps (#123). Closing this issue to focus discussions on these specific areas.
