### ISSUE TITLE
Change humans default generation time to 27 years

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#96]
Currently 25, but 

> I've taken 27 years as a better default (reflecting long-term averages, maybe) for humans:
http://dx.doi.org/10.1002/ajpa.20188I've taken 27 years as a better default (reflecting long-term averages, maybe) for humans:
http://dx.doi.org/10.1002/ajpa.20188

**Comment by jeromekelleher** [comment]
Also, this should be a documented property in the module with the reference included.

**Comment by apragsdale** [comment]
Most of these models were inferred using genetic units and then converted to physical units using an assumed generation time. Some models, like Gutenkunst et al, use generation time of 25 years. More recent models have used 27 or 29 years to rescale. Since these papers typically report rescaled units, they are specific to the assumed generation time, I think? So changing the default time will change expectations under the models.

(related, implementing a model that used a generation time of 29 years would require re-rescaling reported parameters if we want to maintain a consistent default generation time across models)

**Comment by jeromekelleher** [comment]
We've set it up so that models can defined with a specific generation but, which they use internally. The default generation time is then something that's associated with the species, and can be used if there's no particular generation time specified in a particular model.

**Comment by jeromekelleher** [comment]
Superseded by #289.
